### ISSUE TITLE
Update Apache Storm

### ISSUE THREAD

**Issue by coy123** [acdh-oeaw/stormychecker#4]
Apache Storm used for Stormcrawler is version 1.2 but Apache Strom latest version is >=2.

**Comment by twagoo** [comment]
Storm crawler v2.0 uses Storm 2.x. See https://github.com/DigitalPebble/storm-crawler/compare/1.16...2.0

**Comment by twagoo** [comment]
Replaced by https://github.com/clarin-eric/linkchecker/issues/1

**Comment by wowasa** [comment]
transfered to linkchecker
