### ISSUE TITLE
Use the checker to monitor PIDs from B-centres

### ISSUE THREAD

**Issue by dietervu** [acdh-oeaw/stormychecker#8]
A monitoring mechanism for PIDs from registered B-centres is needed. Find out how to create alerts based on such a check. Could e.g. be connected to Icinga or Statuscake.

**Comment by twagoo** [comment]
Replaced by https://github.com/clarin-eric/linkchecker/issues/4

**Comment by wowasa** [comment]
transfered to linkchecker
